### ISSUE TITLE
如果想双击打开powershell,该怎么设置？

### ISSUE THREAD

**Issue by twsec-pro** [tyB-or/FreeGui#1]
如果想双击打开powershell,该怎么设置？默认是打开cmd，如果想修改为打开powershell如何设置

**Comment by tyB-or** [comment]
工具目前没有该功能，但是我已经有了当前代码的解决思路：
方案1：完全放开执行命令的编辑权限，可以通过界面修改启动命令的方式直接指定用powershell打开并运行，不指定默认是cmd。
方案2：增加ini文件属性，type=powershell，然后修改代码中的启动逻辑，启动前检查该属性，有就使用powershell打开。

相关代码：
openToolCmd()方法

使用powershell打开工具代码参考：
subprocess.Popen(  ' start powershell -NoExit cd  toolpath  &&  startcommand '  , shell=True)

目前计划后期如果需要，会优化这个问题。除此之外，当前可能需要自己按照原来的方式打开相关工具
