### ISSUE TITLE
工具无法启动

### ISSUE THREAD

**Issue by xyongsec** [tyB-or/FreeGui#3]
![image](https://user-images.githubusercontent.com/48509164/209254819-da37db6b-4ffb-4f20-b3f5-175d99ba3d1d.png)

**Comment by tyB-or** [comment]
#常见问题：
#1.工具的名称不对，会默认进入工具的cmd界面
#2.启动命令错误，双击启动会没有反应，可以用python  gui.py，在控制台查看报错信息
按照上面的检查下

**Comment by xyongsec** [comment]
![image](https://user-images.githubusercontent.com/48509164/209262029-90d90b22-e0e2-4fcf-b532-caa8542bea3b.png)
名称和运行命令 都没有问题

**Comment by tyB-or** [comment]
你的java环境是8的吗

**Comment by tyB-or** [comment]
你的java环境是8的吗

**Comment by xyongsec** [comment]
是的   但是工具在命令行 使用 java8  可以正常运行

**Comment by tyB-or** [comment]
我来远程看看，1989655061

**Comment by tyB-or** [comment]
问题记录：
现象：读取配置文件的时候自动吃掉一层目录，导致读取启动命令配置文件失败，进而导致即使正确填写启动命令也无法启动工具。
分析：问题出现环境：win10，python3.7--(我本机win11,python3.10+)，初步判断可能是python版本导致，其内部自带库函数功能发生变化，等下午小伙伴更新py版本试试

**Comment by xyongsec** [comment]
推荐使用 python3.10.0 版本，解决读取配置文件问题，正常运行。
