### ISSUE TITLE
作者联系方式有吗

### ISSUE THREAD

**Issue by yichensec** [tyB-or/FreeGui#4]
你好，我挺喜欢你这个工具的框架的，我自己也用了ttkbootstrap二开了一下漏洞仓库 ,存储个人工具，还有个22年的漏洞exp仓库项目，感觉不太友好，可以加你个微信，交流一下吗

**Comment by yichensec** [comment]
@tyB-or
![搜狗截图20221226171533](https://user-images.githubusercontent.com/112226904/209531297-66085a66-952c-4b5d-b042-ab040228e5df.jpg)
![搜狗截图20221226171546](https://user-images.githubusercontent.com/112226904/209531345-42ee4327-a380-4147-a4c7-211f73a20fb9.jpg)

**Comment by tyB-or** [comment]
我加你把

**Comment by yichensec** [comment]
vx：yichensec
